### PR TITLE
Lego Peach advertised system type

### PR DESCRIPTION
**Pull request by mutesplash**
Based on physical hardware BTLE advertisement data

### CODE REVIEW

**Comment by mutesplash** [comment]
I don't know what LEAF is about, though, so I didn't put that in

**Comment by dlech** [comment]
Thanks!. "LEAF" is the model number found in the battery compartment if you want to have a look there.

**Comment by mutesplash** [comment]
Interesting.  I checked and updated the patch.

**Comment by dlech** [comment]
Merged, thanks!

**Pull request merged**
